#!/bin/bash

rm -v ./*.aux > /dev/null 2>&1
rm -v ./*.log > /dev/null 2>&1
rm -v ./*.nav > /dev/null 2>&1
rm -v ./*.out > /dev/null 2>&1
rm -v ./*.snm > /dev/null 2>&1
rm -v ./*.toc > /dev/null 2>&1
rm -v ./*.bbl > /dev/null 2>&1
rm -v ./*.blg > /dev/null 2>&1
rm -v ./*.idx > /dev/null 2>&1
rm -v ./*.ilg > /dev/null 2>&1
rm -v ./*.ind > /dev/null 2>&1
rm -v ./*.tcp > /dev/null 2>&1
rm -v ./*.vrb > /dev/null 2>&1
rm -v ./*.tps > /dev/null 2>&1
rm -v ./*.log > /dev/null 2>&1
rm -v ./*.lot > /dev/null 2>&1
rm -v ./*.synctex.gz > /dev/null 2>&1
rm -v ./*.fls > /dev/null 2>&1
rm -v ./*.fdb_latexmk > /dev/null 2>&1
rm -v ./*.vscodeLog > /dev/null 2>&1
rm -v ./*.log > /dev/null 2>&1
rm -v ./*.bcf > /dev/null 2>&1
rm -v ./*.glo > /dev/null 2>&1
rm -v ./*.glsdefs > /dev/null 2>&1
rm -v ./*.ist > /dev/null 2>&1
rm -v ./*.lof > /dev/null 2>&1
rm -v ./*.run.xml > /dev/null 2>&1
